version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    environment:
      JVM_OPTS: -Xmx3200m
        
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Assemble
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apks
      - run:
          name: Run Tests
          command: ./gradlew lintDebug testDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run: echo $ENCODED_KEYSTORE | base64 --decode >> ${HOME}/repo/keystore.jks
      - run: echo 'export KEYSTORE=${HOME}/repo/keystore.jks' >> $BASH_ENV
      - run:
          name: Assemble release
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: apks